--- 
- name: Generating user detail documentation pages
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/vault/docs/users_detail_{{ ivar_userid }}.rst"
    mode: 0644
  with_first_found:
    - "group_files/servers/users_detail.rst.j2"
    - "{{ role_path }}/templates/users_detail.rst.j2"
  run_once: true
  delegate_to: localhost