---

- name: "User '{{ ivar_userid }}': Generating user detail documentation page"
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/users/detail_{{ ivar_userid }}.rst"
    mode: 0644
  with_first_found:
    - "inventory/group_files/servers/users_detail.rst.j2"
    - "{{ role_path }}/templates/users_detail.rst.j2"
  delegate_to: localhost
  run_once: true