---

- name: Detecting additional host documentation snippets
  find:
    paths: "{{ playbook_dir }}/host_files/{{ inventory_hostname}}/docs"
    patterns: '_inc_description.rst'
    file_type: file
  delegate_to: localhost
  register: hmui__inc_description

- name: Managing local directory for documentation pages
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}"
    - "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/dokuwiki"
    - "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/inventory"
    - "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/users"
  delegate_to: localhost
  run_once: true

- name: Generating inventory overview documentation page
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/section_01_inventory.rst"
    mode: 0644
  with_first_found:
    - "group_files/servers/inventory.rst.j2"
    - "{{ role_path }}/templates/inventory.rst.j2"
  delegate_to: localhost
  run_once: true
  notify:
    - Rebuild documentation

- name: Generating inventory overview documentation page (dokuwiki)
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/dokuwiki/inventory.dokuwiki"
    mode: 0644
  with_first_found:
    - "group_files/servers/inventory.dokuwiki.j2"
    - "{{ role_path }}/templates/inventory.dokuwiki.j2"
  delegate_to: localhost
  run_once: true

- name: Generating environment dump documentation page
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/envdump.rst"
    mode: 0644
  with_first_found:
    - "group_files/servers/envdump.rst.j2"
    - "{{ role_path }}/templates/envdump.rst.j2"
  delegate_to: localhost
  run_once: true
  notify:
    - Rebuild documentation

- name: Generating inventory detail documentation page
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/inventory/detail_{{ inventory_hostname }}.rst"
    mode: 0644
  with_first_found:
    - "host_files/{{ inventory_hostname }}/inventory_detail.rst.j2"
    - "group_files/servers-{{ msms_server_type }}/inventory_detail.rst.j2"
    - "group_files/servers/inventory_detail.rst.j2"
    - "{{ role_path }}/templates/inventory_detail.rst.j2"
  delegate_to: localhost
  notify:
    - Rebuild documentation

- name: Generating inventory dump documentation page
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/inventory/dump_{{ inventory_hostname }}.rst"
    mode: 0644
  with_first_found:
    - "host_files/{{ inventory_hostname }}/inventory_dump.rst.j2"
    - "group_files/servers-{{ msms_server_type }}/inventory_dump.rst.j2"
    - "group_files/servers/inventory_dump.rst.j2"
    - "{{ role_path }}/templates/inventory_dump.rst.j2"
  delegate_to: localhost
  notify:
    - Rebuild documentation
