---

- name: Detecting additional host documentation snippets
  find:
    paths: "{{ playbook_dir }}/inventory/host_files/{{ inventory_hostname}}/honzamach.util_inspector"
    patterns: '_inc_description.rst'
    file_type: file
  delegate_to: localhost
  register: hmui__inc_description

- name: Managing local directory for documentation pages
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}"
    - "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/dokuwiki"
    - "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/envdump"
    - "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/inventory"
    - "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/monitoring"
    - "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/users"
  delegate_to: localhost
  run_once: true

- name: Generating inventory overview documentation page
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/section_01_inventory.rst"
    mode: 0644
  with_first_found:
    - "inventory/group_files/servers/honzamach.util_inspector/inventory.rst.j2"
    - "{{ role_path }}/templates/inventory.rst.j2"
  delegate_to: localhost
  run_once: true
  notify:
    - Rebuild documentation

- name: Generating inventory overview documentation page (dokuwiki)
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/dokuwiki/inventory.dokuwiki"
    mode: 0644
  with_first_found:
    - "inventory/group_files/servers/honzamach.util_inspector/inventory.dokuwiki.j2"
    - "{{ role_path }}/templates/inventory.dokuwiki.j2"
  delegate_to: localhost
  run_once: true

- name: Generating environment dump documentation page
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/section_99_envdump.rst"
    mode: 0644
  with_first_found:
    - "inventory/group_files/servers/honzamach.util_inspector/envdump.rst.j2"
    - "{{ role_path }}/templates/envdump.rst.j2"
  delegate_to: localhost
  run_once: true
  notify:
    - Rebuild documentation

- name: Generating inventory detail documentation page
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/inventory/detail_{{ inventory_hostname }}.rst"
    mode: 0644
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.util_inspector/inventory_detail.rst.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.util_inspector/inventory_detail.rst.j2"
    - "inventory/group_files/servers/honzamach.util_inspector/inventory_detail.rst.j2"
    - "{{ role_path }}/templates/inventory_detail.rst.j2"
  delegate_to: localhost
  notify:
    - Rebuild documentation

- name: Generating inventory dump documentation page
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/envdump/detail_{{ inventory_hostname }}.rst"
    mode: 0644
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.util_inspector/envdump_detail.rst.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.util_inspector/envdump_detail.rst.j2"
    - "inventory/group_files/servers/honzamach.util_inspector/envdump_detail.rst.j2"
    - "{{ role_path }}/templates/envdump_detail.rst.j2"
  delegate_to: localhost
  notify:
    - Rebuild documentation

#-------------------------------------------------------------------------------

- name: Generating user overview documentation page
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/section_02_users.rst"
    mode: 0644
  with_first_found:
    - "inventory/group_files/servers/honzamach.util_inspector/users.rst.j2"
    - "{{ role_path }}/templates/users.rst.j2"
  run_once: true
  delegate_to: localhost

- include_tasks: _func.inspect_user.yml
  vars:
    ivar_userid: "{{ outer_item.0 }}"
    ivar_userdata: "{{ outer_item.1 }}"
  loop: "{{ site_users | dictsort }}"
  loop_control:
    loop_var: outer_item
    label: "Inspecting user {{ outer_item.0 }}"

#-------------------------------------------------------------------------------

- block:

    - name: Detecting list of available Nagios NRPE commands
      shell: "grep -v \"^\\s*#\" /etc/nagios/nrpe.cfg /etc/nagios/nrpe_local.cfg /etc/nagios/nrpe.d/*.cfg | grep \"command\\[\" | sed 's/.*:command\\[//' | sed 's/\\]=.*//'"
      register: current_nrpe_commands
      changed_when: False

    - debug: var=current_nrpe_commands
      tags:
        - debug

    - set_fact:
        current_nrpe_command_list: "{{ current_nrpe_commands.stdout_lines }}"

    - debug: var=current_nrpe_command_list
      tags:
        - debug

    - name: Generating monitoring overview documentation page
      template:
        src: "{{ item }}"
        dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/section_03_monitoring.rst"
        mode: 0644
      with_first_found:
        - "inventory/group_files/servers/honzamach.util_inspector/monitoring.rst.j2"
        - "{{ role_path }}/templates/monitoring.rst.j2"
      run_once: true
      delegate_to: localhost

    - name: Generating monitoring detail documentation pages
      template:
        src: "{{ item }}"
        dest: "{{ playbook_dir }}/{{ hm_util_inspector__docs_dir }}/monitoring/detail_{{inventory_hostname}}.rst"
        mode: 0644
      with_first_found:
        - "inventory/host_files/{{ inventory_hostname }}/honzamach.util_inspector/monitoring_detail.rst.j2"
        - "group_files/servers_{{ msms_server_type }}/honzamach.util_inspector/monitoring_detail.rst.j2"
        - "group_files/servers/honzamach.util_inspector/monitoring_detail.rst.j2"
        - "{{ role_path }}/templates/monitoring_detail.rst.j2"
      delegate_to: localhost

  when: '"servers_monitored" in group_names'

